### ISSUE TITLE
Error installing module in windows PC

### ISSUE THREAD

**Issue by RushabhJoshi** [jlouthan/perspective-transform-js#2]
hey,
First of all very nice work done.
but I have problem installing via npm.(tried on with bower and loved your work)
though I reported problem in npm and npm-windows-update 

Error is something like

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "perspective-transform"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install perspective-transform as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     E:\node\perspective-transform\npm-debug.log

**Comment by jlouthan** [comment]
Sorry you're having issues installing with npm. By any chance is "perspective-transform" the name of your module in your package.json? Take a look at a solution to this issue on SO:  http://stackoverflow.com/questions/27267707/npm-warn-install-refusing-to-install-hapi-as-a-dependency-of-itself
